version: '3.9'

services:
  core: &core
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: core
    volumes:
      - .:/src
    working_dir: /src

  site:
    <<: *core
    ports:
      - 5173:5173
    command: pnpm run dev --host
    container_name: site
